[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "win-64", "linux-64"]
preview = ["pixi-build"]

[dependencies]
python = ">=3.13.5,<3.14"

[pypi-dependencies]
pixi_build_ros = { path = ".", editable = true }
py-pixi-build-backend = { path = "../../py-pixi-build-backend", editable = true }

[package.build]
backend = { name = "pixi-build-python", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[package]
name = "pixi-build-ros"
version = "0.1.2"

[package.host-dependencies]
hatchling = "*"

[package.run-dependencies]
rosdistro = "*"
catkin_pkg = "*"
toml = "*"
pyyaml = "*"
pixi-build-api-version = { path = "../../recipe/pixi-build-api-version" }
py-pixi-build-backend = { path = "../../py-pixi-build-backend" }
