[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["osx-arm64", "win-64", "linux-64"]
preview = ["pixi-build"]

[dependencies]
pytest = "*"
ruff = "*"
pixi-build-ros = { path = "." }

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package]
name = "pixi-build-ros"
version = "0.1.1"

[package.host-dependencies]
hatchling = "*"

[package.run-dependencies]
rosdistro = "*"
catkin_pkg = "*"
pyyaml = "*"
pixi-build-api-version = ">=2,<3"
# should be added to `py-pixi-build-backend`
typing-extensions = "*"
#py-pixi-build-backend = "*"
py-pixi-build-backend = { path = "../../py-pixi-build-backend" }
