[project]
dependencies = [
  "rosdistro",
  "catkin_pkg",
  "pytest",
  "toml",
  "pyyaml",
  "pydantic",
  "py_rattler",
  #  TODO: publish to pypi
  #  "py-pixi-build-backend",
]
name = "pixi-build-ros"
version = "0.3.1"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project.scripts]
pixi-build-ros = "pixi_build_ros.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/pixi_build_ros"]

[tool.hatch.build.targets.wheel.shared-data]
"templates" = "site-packages/pixi_build_ros/templates"
"robostack.yaml" = "site-packages/pixi_build_ros/robostack.yaml"

[tool.hatch.build.targets.editable]
packages = ["src/pixi_build_ros"]

[tool.hatch.build.targets.editable.shared-data]
"templates" = "site-packages/pixi_build_ros/templates"
"robostack.yaml" = "site-packages/pixi_build_ros/robostack.yaml"

[tool.ruff]
line-length = 120
target-version = "py310"
fix = true

[tool.mypy]
python_version = "3.10"
files = ["src/pixi_build_ros"]
strict = true
ignore_missing_imports = true
enable_error_code = ["redundant-expr", "truthy-bool", "ignore-without-code"]
disable_error_code = ["empty-body", "no-untyped-call"]
