[project]
authors = [{name = "Ruben Arts", email = "ruben.arts@hotmail.com"}]
dependencies = []
name = "pixi-build-ros"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
pixi_build_ros = { path = ".", editable = true }
py-pixi-build-backend = { path = "../../py-pixi-build-backend", editable = true }

