[project]
dependencies = [
  "rosdistro",
  "catkin_pkg",
  "pytest",
  "toml",
  "pyyaml",
  "distutils",
]
name = "pixi-build-ros"
version = "0.1.0"

[project.scripts]
pixi-build-ros = "pixi_build_ros.main:main"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
