[package.build.backend]
name = "pixi-build-rust"
version = "*"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[package.run-dependencies]
pixi-build-api-version = ">=2,<3"
