[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
async-trait = "0.1.82"
chrono = "0.4.38"
clap = "4.5.20"
clap-verbosity-flag = "3.0.1"
fs-err = "3.0.0"
indexmap = "2.7.0"
itertools = "0.13.0"
log = "0.4.22"
miette = "7.4.0"
minijinja = "2.4.0"
parking_lot = "0.12.3"
reqwest = "0.12.5"
reqwest-middleware = "0.4.0"
serde = "1.0"
serde_yaml = "0.9"
serde_json = "1.0"
tempfile = "3.10.1"
tokio = "1.37.0"
tracing-subscriber = "0.3.19"
url = "2.5.4"

jsonrpc-stdio-server = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-core = "18.0.0"

rattler-build = { git = "https://github.com/prefix-dev/rattler-build", branch = "main", default-features = false }

rattler_conda_types = { version = "0.29.1", default-features = false }
rattler_package_streaming = { version = "0.22.14", default-features = false }
rattler_virtual_packages = { version = "1.1.10", default-features = false }

pixi_build_types = { git = "https://github.com/nichmor/pixi", branch = "feat/add-git-source-dependencies" }
pixi_consts = { git = "https://github.com/nichmor/pixi", branch = "feat/add-git-source-dependencies" }
pixi_manifest = { git = "https://github.com/nichmor/pixi", branch = "feat/add-git-source-dependencies" }
pixi_spec = { git = "https://github.com/nichmor/pixi", branch = "feat/add-git-source-dependencies" }

[patch.crates-io]
rattler = { git = "https://github.com/conda/rattler", branch = "main" }
rattler_conda_types = { git = "https://github.com/conda/rattler", branch = "main" }
rattler_package_streaming = { git = "https://github.com/conda/rattler", branch = "main" }
rattler_virtual_packages = { git = "https://github.com/conda/rattler", branch = "main" }
rattler_cache = { git = "https://github.com/conda/rattler", branch = "main" }
rattler_solve = { git = "https://github.com/conda/rattler", branch = "main" }
rattler_repodata_gateway = { git = "https://github.com/conda/rattler", branch = "main" }
rattler_redaction = { git = "https://github.com/conda/rattler", branch = "main" }
rattler_networking = { git = "https://github.com/conda/rattler", branch = "main" }
