site_name: "Pixi Build Backends"
site_url: https://prefix-dev.github.io/pixi-build-backends

theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/pixi.png
  logo: assets/pixi.png
  font:
    text: Red Hat Text
    code: JetBrains Mono

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: prefix-light
      accent: prefix-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: prefix
      accent: prefix
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    edit: material/pencil
    view: material/eye

  features:
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.code.annotate
    - content.tooltips
    # - content.code.select Sponsor only
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.footer

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/prefix-dev/pixi-build-backends
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - abbr
  - def_list
  - footnotes
  - attr_list
  - pymdownx.extra
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 3
      permalink: "#"
  - mdx_truly_sane_lists

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prefix-dev
    - icon: fontawesome/brands/mastodon
      link: https://hachyderm.io/@prefix
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/prefix.dev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/prefix-dev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/prefix_dev

nav:
  - Home: index.md
  - Backends:
    - pixi-build-cmake: backends/pixi-build-cmake.md
    - pixi-build-python: backends/pixi-build-python.md
    - pixi-build-rattler-build: backends/pixi-build-rattler-build.md
    - pixi-build-rust: backends/pixi-build-rust.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
