[workspace]
authors = ["Nichita Morcotilo <nichita@prefix.dev>"]
channels = ["conda-forge"]
description = "Showcases how to build a rattler-build recipe  with pixi"
name = "pixi-build-rattler-build"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

[package]
authors = ["Nichita Morcotilo <nichita@prefix.dev>"]
description = "Showcases how to build a rattler-build recipe with pixi"
name = "pixi-build-rattler-build"
version = "0.1.8"


[dependencies]
pixi-build-rattler-build = { path = "." }

[package.build]
backend = { name = "pixi-build-rust", version = "==0.1.10" }
channels = ["https://prefix.dev/pixi-build-backends", "conda-forge"]

[package.target.unix.host-dependencies]
openssl = "*"
