[workspace]
channels = ["https://prefix.dev/conda-forge"]
preview = ["pixi-build"]

[package]
name = "pixi-build-rattler-build"
version = "0.3.2"

[package.build]
backend = { name = "pixi-build-rust", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
