[workspace]
authors = ["Nichita Morcotilo <nichita@prefix.dev>"]
channels = ["conda-forge"]
description = "Showcases how to build a cpp project with pixi"
name = "pixi-build-cmake"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

[package]
authors = ["Nichita Morcotilo <nichita@prefix.dev>"]
description = "Showcases how to build a cpp project with pixi"
name = "pixi-build-cmake"
version = "0.1.6"


[dependencies]
pixi-build-cmake = { path = "." }

[package.build]
backend = { name = "pixi-build-rust", version = "*" }
channels = ["https://prefix.dev/pixi-build-backends", "conda-forge"]

[package.target.unix.host-dependencies]
openssl = "*"
