# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: py-pixi-build-backend
  version: "${{ env.get('PY_PIXI_BUILD_BACKEND_VERSION', default='0.1.0dev') }}"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ../..

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.2.2,<2
    - ${{ compiler('rust') }}
  host:
    - python
    - python-abi3
    - maturin >=1.2.2,<2
    - pip

  run:
    - python >=3.8
    - pixi-build-api-version >=2,<3
  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}

build:
  script:
    - cd py-pixi-build-backend
    - pip install . -vv --no-build-isolation
  python:
    version_independent: true

tests:
  - python:
      imports:
        - pixi_build_backend

about:
  homepage: https://github.com/prefix-dev/pixi-build-backends
  summary: Python bindings for pixi-build-backends
  description: |
    This package provides Python bindings for pixi-build-backends, enabling
    Python applications to use the pixi build system programmatically.
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://prefix-dev.github.io/pixi-build-backends
  repository: https://github.com/prefix-dev/pixi-build-backends
