name: Python bindings CI

on:
  push:
    branches: [main]
  pull_request:
    paths:
      # When we change code that bindings depend on, we want to ensure that the maturin builds still work
      - crates/pixi-build-backend/**
      - Cargo.*

      # When something in the bindings themselves changes
      - py-pixi-build-backend/**/*

      # Or when this workflow changes
      - .github/workflows/python-bindings.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format_lint_test:
    name: Format, Lint and Test the Python bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - uses: prefix-dev/setup-pixi@8ca4608ef7f4daeb54f5205b20d0b7cb42f11143 # v0.8.14
        with:
          manifest-path: py-pixi-build-backend/pixi.toml
          environments: test
      - uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1.13.0
        with:
          components: clippy, rustfmt
      - name: Format and Lint
        run: |
          cd py-pixi-build-backend
          pixi run -e test lint
          pixi run -e test fmt-check
      - name: Run tests
        run: |
          cd py-pixi-build-backend
          pixi run -e test test --color=yes
